---
title: "Quiz 1"
author: "Amy Su Jiang"
output: html_document
---

### Question 1

Which of the following are steps in building a machine learning algorithm?

    Collecting data to answer the question.
    Artificial intelligence
    Machine learning
    Statistical inference

### Question 2

Suppose we build a prediction algorithm on a data set and it is 100% accurate on that data set. Why might the algorithm not work well if we collect a new data set?

    We may be using a bad algorithm that doesn't predict well on this kind of data.
    We have used neural networks which has notoriously bad performance.
    We have too few predictors to get good out of sample accuracy.
    Our algorithm may be overfitting the training data, predicting both the signal and the noise.

### Question 3

What are typical sizes for the training and test sets?

    60% in the training set, 40% in the testing set.
    80% training set, 20% test set
    20% test set, 80% training set.
    90% training set, 10% test set

### Question 4

What are some common error rates for predicting binary variables (i.e. variables with two possible values like yes/no, disease/normal, clicked/didn't click)?

    Correlation
    Specificity
    P-values
    Root mean squared error

### Question 5

Suppose that we have created a machine learning algorithm that predicts whether a link will be clicked with 99% sensitivity and 99% specificity. The rate the link is clicked is 1/1000 of visits to a website. If we predict the link will be clicked on a specific visit, what is the probability it will actually be clicked?

    99%
    50%
    9%
    0.009%
